# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MemorialInterativo
                                 A QGIS plugin
 Gera memorial descritivo capturando confrontantes com cliques no mapa e exporta tabela de coordenadas em DXF, modelo topograph
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-13
        copyright            : (C) 2026 by Thiago Norio Santos Igarashi
        email                : thiago.igarashi@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MemorialInterativo class from file MemorialInterativo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .memorial_interativo import MemorialInterativo
    return MemorialInterativo(iface)
